<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\FaultCodes;
class FaultCodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faultCodes = [
            ['code' => '1.5', 'description' => '1.5x SHAFT'],
            ['code' => '2.5', 'description' => '2.5x SHAFT'],
            ['code' => '3.5', 'description' => '3.5x SHAFT'],
            ['code' => '4.5', 'description' => '4.5x SHAFT'],
            ['code' => '5.5', 'description' => '5.5x SHAFT'],
            ['code' => '6.5', 'description' => '6.5x SHAFT'],
            ['code' => '60', 'description' => '60 HERTZ'],
            ['code' => '120', 'description' => '120 HERTZ'],
            ['code' => '180', 'description' => '180 HERTZ'],
            ['code' => '240', 'description' => '240 HERTZ'],
            ['code' => '360', 'description' => '360 HERTZ'],
            ['code' => '420', 'description' => 'SPECIFIED 60 HZ HARMONICS'],
            ['code' => '480', 'description' => 'SPECIFIED 60 HZ HARMONICS'],
            ['code' => '540', 'description' => 'SPECIFIED 60 HZ HARMONICS'],
            ['code' => '660', 'description' => 'SPECIFIED 60 HZ HARMONICS'],
            ['code' => '720', 'description' => '720 HERTZ'],
            ['code' => '1X', 'description' => '1X SHAFT'],
            ['code' => '1XA', 'description' => '1X AUX DRIVE SHAFT'],
            ['code' => '1XB', 'description' => '1X PURIFIER BOWL SHAFT'],
            ['code' => '1XC', 'description' => '1X COMPRESSOR SHAFT'],
            ['code' => '1XD', 'description' => '1X DIESEL SHAFT'],
            ['code' => '1XE', 'description' => '1X EXCITER SHAFT'],
            ['code' => '1XF', 'description' => '1X FAN SHAFT'],
            ['code' => '1XG', 'description' => '1X GENERATION SHAFT'],
            ['code' => '1XH', 'description' => '1X HI PRESS TURB SHAFT'],
            ['code' => '1XI', 'description' => '1X INTERMEDIATE SHAFT'],
            ['code' => '1XJ', 'description' => '1X BELT OUTPUT / GEAR INPUT'],
            ['code' => '1XK', 'description' => '1X GEAR OUTPUT / BELT INPUT'],
            ['code' => '1XL', 'description' => '1X LO PRESS TURBINE SHAFT'],
            ['code' => '1XM', 'description' => '1X MOTOR SHAFT'],
            ['code' => '1XN', 'description' => '1X SPINDLE SHAFT'],
            ['code' => '1XO', 'description' => '1X OUTPUT OR OIL PMP SHAFT'],
            ['code' => '1XP', 'description' => '1X PUMP SHAFT'],
            ['code' => '1XQ', 'description' => '1X SCREW SHAFT'],
            ['code' => '1XR', 'description' => '1X IDLER SHAFT'],
            ['code' => '1XS', 'description' => '1X PROPELLER LINE SHAFT'],
            ['code' => '1XT', 'description' => '1X TURBINE SHAFT'],
            ['code' => '1XV', 'description' => '1X GOVERNOR SHAFT'],
            ['code' => '1XW', 'description' => '1X BLOWER SHAFT'],
            ['code' => '20G', 'description' => '2 X OIL PUMP GEAR MESH HARMONIC'],
            ['code' => '30G', 'description' => '3 X OIL PUMP GEAR MESH HARMONIC'],
            ['code' => '40G', 'description' => '4 X OIL PUMP GEAR MESH HARMONIC'],
            ['code' => 'AG', 'description' => 'AUX DRIVE GEAR MESH'],
            ['code' => 'BL', 'description' => 'BLOWER LOBES'],
            ['code' => 'BR', 'description' => 'BELT ROTATION'],
            ['code' => 'GB', 'description' => 'GENERATOR BARS'],
            ['code' => 'GBS', 'description' => 'GENERATOR BEARING SHOES'],
            ['code' => 'GFB', 'description' => 'GENERATOR FAN BLADES'],
            ['code' => 'GR', 'description' => 'MAIN GEAR MESH'],
            ['code' => 'GR1', 'description' => '1st GEAR MESH (Only use on Cent Cprsrs)'],
            ['code' => 'GR2', 'description' => '2nd GEAR MESH (Only use on Cent Cprsrs)'],
            ['code' => 'GR3', 'description' => '3rd GEAR MESH (Only use on Cent Cprsrs)'],
            ['code' => 'GR4', 'description' => '4th GEAR MESH (Only use on Cent Cprsrs)'],
            ['code' => 'GS', 'description' => 'GENERATOR SLOTS'],
            ['code' => 'GV', 'description' => 'COMPRESSOR GUIDE VANES'],
            ['code' => 'GV1', 'description' => '1ST STAGE GUIDE VANES'],
            ['code' => 'GV2', 'description' => '2nd STAGE GUIDE VANES'],
            ['code' => 'GV3', 'description' => '3rd STAGE GUIDE VANES'],
            ['code' => 'GV4', 'description' => '4th STAGE GUIDE VANES'],
            ['code' => 'GVG', 'description' => 'GOVERNOR DRIVE GEAR MESH'],
            ['code' => 'HCG', 'description' => 'HI SPEED SHAFT COUPLING ELEMENTS'],
            ['code' => 'HG', 'description' => 'HI SPEED GEAR MESH'],
            ['code' => 'HHG', 'description' => 'HP TURB, HIGH SPEED GEAR MESH'],
            ['code' => 'HOP', 'description' => 'HI SPEED OIL PUMP ELEMENTS'],
            ['code' => 'HYD', 'description' => 'HYDRAULIC EXCITATION (EXTERNAL)'],
            ['code' => 'I1', 'description' => '1ST INTERMEDIATE SHAFT'],
            ['code' => 'I2', 'description' => '2nd INTERMEDIATE SHAFT'],
            ['code' => 'I3', 'description' => '3rd INTERMEDIATE SHAFT'],
            ['code' => 'I4', 'description' => '4th INTERMEDIATE SHAFT'],
            ['code' => 'I5', 'description' => '5th INTERMEDIATE SHAFT'],
            ['code' => 'LCG', 'description' => 'LO SPEED SHAFT COUPLING ELEMENTS'],
            ['code' => 'LF2', 'description' => 'TWICE LINE FREQUENCY (VFD ONLY)'],
            ['code' => 'LG', 'description' => 'LOW SPEED GEAR MESH'],
            ['code' => 'LHG', 'description' => 'LP TURB, HIGH SPEED GEAR MESH'],
            ['code' => 'LOP', 'description' => 'LO SPEED OIL PUMP ELEMENTS'],
            ['code' => 'MB', 'description' => 'MOTOR ROTOR BARS'],
            ['code' => 'MB1', 'description' => 'MOTOR BARS +/- 120 HZ'],
            ['code' => 'MB2', 'description' => 'MOTOR BARS +/- 240 HZ'],
            ['code' => 'MB3', 'description' => 'MOTOR BARS +/- 360 HZ'],
            ['code' => 'MFB', 'description' => 'MOTOR FAN ROTOR BLADES'],
            ['code' => 'MOP', 'description' => 'MOTOR OIL PUMP ELEMENTS'],
            ['code' => 'NOZ', 'description' => 'TURBINE NOZZLES'],
            ['code' => 'OPG', 'description' => 'OIL PUMP DRIVE GEAR MESH'],
            ['code' => 'OPT', 'description' => 'OIL PUMP ROTOR TEETH'],
            ['code' => 'OPV', 'description' => 'OIL PUMP ROTOR VANES'],
            ['code' => 'P2', 'description' => 'PUMP IDLER ROTOR SHAFT'],
            ['code' => 'PB', 'description' => 'PUMP ROTOR BLADES'],
            ['code' => 'PBS', 'description' => 'PUMP BEARING SHOES'],
            ['code' => 'PG', 'description' => 'PLANETARY GEAR MESH'],
            ['code' => 'PGR', 'description' => 'DECANTER GEAR MESH'],
            ['code' => 'BRG', 'description' => 'SPECIFIED BEARING TONE'],
            ['code' => 'C1', 'description' => 'HP COMPRESSOR SHAFT RATE'],
            ['code' => 'C2', 'description' => 'LP COMPRESSOR SHAFT RATE'],
            ['code' => 'C3', 'description' => '3RD STAGE SHAFT RATE'],
            ['code' => 'C4', 'description' => '4TH STAGE SHAFT RATE'],
            ['code' => 'CFB', 'description' => 'COMPRESSOR FAN BLADES'],
            ['code' => 'CG', 'description' => 'COUPLING ELEMENTS'],
            ['code' => 'CL', 'description' => 'CLUTCH ELEMENTS'],
            ['code' => 'CMG', 'description' => 'CAM SHAFT GEAR MESH'],
            ['code' => 'CML', 'description' => 'CAM SHAFT LOBES'],
            ['code' => 'COG', 'description' => 'COMPRESSOR OIL PMP GEAR MESH'],
            ['code' => 'COP', 'description' => 'COMP SHAFT OIL PUMP ELEMENTS'],
            ['code' => 'CP', 'description' => 'COMPRESSOR PISTONS'],
            ['code' => 'CR', 'description' => 'CHAIN ROTATION'],
            ['code' => 'CS', 'description' => 'COMMUTATOR SEGMENTS'],
            ['code' => 'CS1', 'description' => '1ST STAGE COMPRESSOR SHAFT'],
            ['code' => 'CS2', 'description' => '2nd STAGE COMPRESSOR SHAFT'],
            ['code' => 'CS3', 'description' => '3rd STAGE COMPRESSOR SHAFT'],
            ['code' => 'CS4', 'description' => '4th STAGE COMPRESSOR SHAFT'],
            ['code' => 'CT', 'description' => 'COMPRESSOR THREADS'],
            ['code' => 'CT1', 'description' => 'HP COMPRESSOR THREADS'],
            ['code' => 'CT2', 'description' => 'LP COMPRESSOR THREADS'],
            ['code' => 'CV', 'description' => 'COMPRESSOR ROTOR VANES'],
            ['code' => 'CV1', 'description' => '1ST STAGE COMPRESSOR VANES'],
            ['code' => 'CV2', 'description' => '2nd STAGE COMPRESSOR VANES'],
            ['code' => 'CV3', 'description' => '3rd STAGE COMPRESSOR VANES'],
            ['code' => 'CV4', 'description' => '4th STAGE COMPRESSOR VANES'],
            ['code' => 'DV', 'description' => 'PUMP DIFFUSER VANES'],
            ['code' => 'EB', 'description' => 'EXCITER BARS'],
            ['code' => 'EF', 'description' => 'ENGINE FIRING RATE'],
            ['code' => 'EM', 'description' => 'ENGINE MISFIRE'],
            ['code' => 'EP', 'description' => 'ENGINE PISTONS'],
            ['code' => 'ES', 'description' => 'EXCITER SLOTS'],
            ['code' => 'F1', 'description' => 'SSTG EXTERNAL EXCITATION'],
            ['code' => 'F2', 'description' => 'SSTG GEN EXTERNAL EXCITATION'],
            ['code' => 'F3', 'description' => 'PROP BLADE RATE EXCITATION'],
            ['code' => 'F4', 'description' => 'HPAC EXCITATION'],
            ['code' => 'F6', 'description' => 'EXTERNAL EXCITATION GENERIC'],
            ['code' => 'F7', 'description' => 'LP TURBINE EXTERNAL EXCITATION'],
            ['code' => 'F8', 'description' => 'HP TURBINE EXCITIATON'],
            ['code' => 'F12', 'description' => 'A/C COMPRESSOR EXTRNL EXCITATION'],
            ['code' => 'F14', 'description' => 'RED GEAR MESH EXTRNL EXCITATION'],
            ['code' => 'F15', 'description' => '2 STROKE DIESEL ENGINE EXCITATION'],
            ['code' => 'F16', 'description' => '4 STROKE DIESEL ENGINE EXCITATION'],
            ['code' => 'FB', 'description' => 'FAN ROTOR BLADES'],
            ['code' => 'FB1', 'description' => '1st STAGE FAN ROTOR BLADES'],
            ['code' => 'FB2', 'description' => '2nd STAGE FAN ROTOR BLADES'],
            ['code' => 'FB3', 'description' => '3rd STAGE FAN ROTOR BLADES'],
            ['code' => 'PP', 'description' => 'PUMP PISTONS'],
            ['code' => 'PT', 'description' => 'PUMP ROTOR THREADS'],
            ['code' => 'PV', 'description' => 'PUMP ROTOR VANES'],
            ['code' => 'PV1', 'description' => '1ST STAGE PUMP ROTOR VANES'],
            ['code' => 'PV2', 'description' => '2nd STAGE PUMP ROTOR VANES'],
            ['code' => 'PV3', 'description' => '3rd STAGE PUMP ROTOR VANES'],
            ['code' => 'PV4', 'description' => '4th STAGE PUMP ROTOR VANES'],
            ['code' => 'PV5', 'description' => '5th STAGE PUMP ROTOR VANES'],
            ['code' => 'R+G', 'description' => 'CPRSR ROTOR + GUIDE VANES'],
            ['code' => 'R1', 'description' => 'HP COMPRESSOR IDLER SHAFT'],
            ['code' => 'R2', 'description' => 'LP COMPRESSOR IDLER SHAFT'],
            ['code' => 'RG', 'description' => 'REVERSING GEAR MESH'],
            ['code' => 'RPT', 'description' => 'REPLINISHING PUMP TEETH'],
            ['code' => 'RPV', 'description' => 'REPLINISHING PUMP VANES'],
            ['code' => 'S1', 'description' => '1ST STAGE COMPRESSOR SHAFT'],
            ['code' => 'S2', 'description' => '2nd STAGE COMPRESSOR SHAFT'],
            ['code' => 'S3', 'description' => '3rd STAGE COMPRESSOR SHAFT'],
            ['code' => 'S4', 'description' => '4th STAGE COMPRESSOR SHAFT'],
            ['code' => 'SP', 'description' => 'SPROCKET MESH'],
            ['code' => 'SPR', 'description' => 'SPRING HOUSING AND BUFFERS'],
            ['code' => 'TB1', 'description' => '1ST STAGE TURBINE ROTOR BLADES'],
            ['code' => 'TB2', 'description' => '2nd STAGE TURBINE ROTOR BLADES'],
            ['code' => 'TB3', 'description' => '3rd STAGE TURBINE ROTOR BLADES'],
            ['code' => 'TB4', 'description' => '4th STAGE TURBINE ROTOR BLADES'],
            ['code' => 'TB5', 'description' => '5th STAGE TURBINE ROTOR BLADES'],
            ['code' => 'TB6', 'description' => '6th STAGE TURBINE ROTOR BLADES'],
            ['code' => 'TBK', 'description' => 'TURBINE BUCKETS'],
            ['code' => 'TBL', 'description' => 'TURBINE ROTOR BLADES'],
            ['code' => 'TBS', 'description' => 'THRUST BEARING SHOES'],
            ['code' => 'TDG', 'description' => 'TURBO DRIVE GEAR MESH'],
            ['code' => 'TG', 'description' => 'TIMING GEAR MESH'],
            ['code' => 'TG1', 'description' => 'HP COMPRESSOR TIMING GEAR MESH'],
            ['code' => 'TG2', 'description' => 'LP COMPRESSOR TIMING GEAR MESH'],
            ['code' => 'TOG', 'description' => 'OIL PUMP GEAR MESH RATE'],
            ['code' => 'TOP', 'description' => 'OIL PUMP ELEMENTS'],
            ['code' => 'TS1', 'description' => '1ST STAGE STATOR BLADES'],
            ['code' => 'TS2', 'description' => '2nd STAGE STATOR BLADES'],
            ['code' => 'TS3', 'description' => '3rd STAGE STATOR BLADES'],
            ['code' => 'TS4', 'description' => '4th STAGE STATOR BLADES'],
            ['code' => 'TS5', 'description' => '5th STAGE STATOR BLADES'],
            ['code' => 'TS6', 'description' => '6th STAGE STATOR BLADES'],
            ['code' => 'TSB', 'description' => 'TURBINE STATOR BLADES'],
            ['code' => 'VFD', 'description' => 'VARIABLE FREQUENCY DRIVE RELATED'],
            ['code' => 'WHP', 'description' => 'WHIP FREQUENCY (Only for Prox Groups)'],
            ['code' => 'WPG', 'description' => 'WATER PUMP GEAR MESH'],
            ['code' => 'WPV', 'description' => 'WATER PUMP VANES'],
            ['code' => 'XCG', 'description' => 'COUPLING RELATED'],
            ['code' => 'XDE', 'description' => 'DIESEL ENGINE RELATED'],
            ['code' => 'FB4', 'description' => '4th STAGE FAN ROTOR BLADES'],
            ['code' => 'FB5', 'description' => '5th STAGE FAN ROTOR BLADES'],
            ['code' => 'FC', 'description' => 'FLUID COUPLING VANES'],
            ['code' => 'FDN', 'description' => 'FOUNDATION VIBRATION'],
            ['code' => 'FPV', 'description' => 'FAN PRE-ROTATION VANES'],
            ['code' => 'FV', 'description' => 'FAN DIFFUSER/STATOR VANE PASS'],
            ['code' => 'FWG', 'description' => 'FLYWHEEL DRIVE GEAR MESH'],
            ['code' => 'G1', 'description' => '1ST GEAR MESH'],
            ['code' => 'G2', 'description' => '2ND GEAR MESH'],
            ['code' => 'G3', 'description' => '3RD GEAR MESH'],
            ['code' => 'G4', 'description' => '4TH GEAR MESH'],
            ['code' => 'G5', 'description' => '5TH GEAR MESH'],
            ['code' => 'G6', 'description' => '6TH GEAR MESH'],
            ['code' => 'XG1', 'description' => '1sT GEAR RELATED'],
            ['code' => 'XG2', 'description' => '2nd GEAR RELATED'],
            ['code' => 'XGR', 'description' => 'MAIN GEAR RELATED'],
            ['code' => 'XHG', 'description' => 'HI SPEED GEAR RELATED'],
            ['code' => 'XLG', 'description' => 'LO SPEED GEAR RELATED'],
        ];

        foreach ($faultCodes as $faultCode) {
            FaultCodes::create($faultCode);
        }
    }
}
